### PR TITLE
Consistency level in projector and store

### PR DESCRIPTION
**Pull request by cottinisimone**
Closes: #82

### CODE REVIEW

**Review by matteosister — APPROVED** [review]

**Review by fabuloso — APPROVED** [review]

**Comment by emturner** [comment]
Hi @cottinisimone!  Hope you're well 😄 

I think that possibly, while this address #82, the implementation is misleading?

Regardless of whether consistency is set to strong or weak, the projectors are *still* running to completion within the transaction - 
The only difference here, is whether projectors are 'allowed' to fail?  So while this does allow you to 'opt in' to allowing projectors to fail, I think the notion of 'consistency' here is perhaps misleading?

Perhaps if consistency is weak, all the projectors should be run separately, in an ideal world? @matteosister 
But possibly this is more effort, as could require larger restructuring of the crate?

(If a projector panics, for any reason, then clearly the event doesn't get persisted at all, but maybe that's not an issue).

**Comment by cottinisimone** [comment]
> Hi @cottinisimone! Hope you're well smile
> 
> I think that possibly, while this address #82, the implementation is misleading?
> 
> Regardless of whether consistency is set to strong or weak, the projectors are _still_ running to completion within the transaction - The only difference here, is whether projectors are 'allowed' to fail? So while this does allow you to 'opt in' to allowing projectors to fail, I think the notion of 'consistency' here is perhaps misleading?
> 
> Perhaps if consistency is weak, all the projectors should be run separately, in an ideal world? @matteosister But possibly this is more effort, as could require larger restructuring of the crate?
> 
> (If a projector panics, for any reason, then clearly the event doesn't get persisted at all, but maybe that's not an issue).

Ops. I've already merged. So what could be a better name for this? `Failability`? `Fallibility`? Don't know honestly

I agree that policies should be outside of the transaction and that if we want to remove the policy concept the new concept should behave like that

**Comment by emturner** [comment]
Don't worry!  My fault for being a bit slow responding to github notifications 😆 

I am also not sure - perhaps something like:
```
/// Governs the relationship of an event to a resulting projection.
pub enum EventPersistence {
   ///  This projector must succeed, for the parent event to be persisted.
   Blocking,
   /// This projector is allowed to fail, and doesn't block persisting the parent event.
   Fallible
}
```

Though I'm not sold on this enum name either!

**Comment by cottinisimone** [comment]
I open an issue for that in order to discuss about that. Thank you very much Emma :)

**Pull request merged**
