### PR TITLE
[PLATFORM-1364]: Migrate to GHA

### PR DESCRIPTION
**Pull request by cottinisimone**
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PLATFORM-1364

### CODE REVIEW

**Comment by cottinisimone** [comment]
We need a `CARGO_AUTH_KEY` usable by the GHA

**Comment by cpiemontese** [comment]
The `continuous-integration/drone/push Expected — Waiting for status to be reported` makes me thing there's something weird with the groups going on

**Comment by cottinisimone** [comment]
> The `continuous-integration/drone/push Expected — Waiting for status to be reported` makes me thing there's something weird with the groups going on

I think it's just a matter of waiting for pulumi up in this PR to be completed: https://github.com/primait/umami

**Comment by cottinisimone** [comment]
> The `continuous-integration/drone/push Expected — Waiting for status to be reported` makes me thing there's something weird with the groups going on

I think that the problem is just that umami tells what the security checks are required. I've merged my PR in umami, but something went wrong with pulumi up..

**Review by MaeIsBad — DISMISSED** [review]

**Review by MaeIsBad — APPROVED** [review]

**Pull request merged**
